version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:11.1.2
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=laravel
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
    volumes:
      - mariadb_data:/bitnami/mariadb

  laravel:
    image: bitnami/laravel:11.6.0
    container_name: laravel
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_DATABASE=laravel
      - DB_PASSWORD=admin
    volumes:
      - ./src:/app
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
